#!/bin/sh

# let's turn this off for now - two cases are failing with the
# upstream code and it's nothitng to do with ECH
# TODO: try this out again in a bit
exit 0

cd $(dirname $0)

export BIN_D=/usr/bin/
export SRCTOP=../../
export BLDTOP=./aa
exec perl -I. 25-test_verify.t
